version: '3.9'
services:
    products-be:
        build: .
        ports:
            - '8000:8000'
        volumes:
            - .:/products-be/
        environment:
            - PORT=8000
            - NODE_ENV=LOCAL
        command: npm run start:dev
        depends_on:
            - products-db
        networks:
            - products-network

    products-db:
        container_name: products-db
        image: postgres
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_DB: products-db
        networks:
            - products-network

networks:
    products-network:
